### ISSUE TITLE
Macos (sequoia?) keyboard not transferred

### ISSUE THREAD

**Issue by SimoneGianni** [input-leap/input-leap#2179]
### What happened?

I installed input leap version 3.0.2 on both my Mac Mini M2 running Sequoia 15.3, acting as a client, and my Macbook 16 x86 i9 running Ventura 13.4, acting as a server.

I can move the mouse from the macbook into the macmini, but the keyboard "remains" on the macbook. Is not captured (what I type is written on the macbook even if I'm moving the mouse on the mini) nor transmitted. 

I was a user of Barrier, didn't use it for long time, then started it today, and had the same issue. Looking for an update I found input leap, but I have the same issue. 

The installation was successful, I authorized input leap permissions, i already closed and reopened input leap on both machines, I rebooted the mini but not the macbook. 

### Version

v3.0.2

### If applicable, where did you install Input Leap from?

https://github.com/input-leap/input-leap/releases

### What OSes are you seeing the problem on? (Check all that apply)

macOS

### What OS versions are you using?

Macod Sequoia 15.3 and Ventura 13.4

### Relevant log output

```shell

```

**Comment by Wisky-pro** [comment]
> On my end, InputLeap doesn't transmit key stroke correctly. I cannot use Command for instance. It's really anoying.

Same here, Only shift and control work, every other function key doesn't get transmitted

**Comment by asidler** [comment]
Simlar problem over here. 'Shift' works but, 'alt' and 'cmd' dont't (InputLeap Version 3.0.2 apple-silicone)

I recorded the following debug1 logs for pressing and releasing 'ctrl', 'alt' and 'cmd' keys on my Mac keyboard (swiss-german layout). 

**Server:**
```
[2025-02-26T15:36:22] DEBUG1: event: Key event kind: 12, keycode=59
[2025-02-26T15:36:22] DEBUG1: mask=40101 outMask=0002
[2025-02-26T15:36:22] DEBUG1: new mask: 0x0002
[2025-02-26T15:36:22] DEBUG1: onKeyDown id=61411 mask=0x0002 button=0x003c
[2025-02-26T15:36:22] DEBUG1: send key down to "lap-asi2.terreactive.ch" id=61411, mask=0x0002, button=0x003c

[2025-02-26T15:36:22] DEBUG1: event: Key event kind: 12, keycode=59
[2025-02-26T15:36:22] DEBUG1: mask=0100 outMask=0000
[2025-02-26T15:36:22] DEBUG1: new mask: 0x0000
[2025-02-26T15:36:22] DEBUG1: onKeyUp id=61411 mask=0x0000 button=0x003c
[2025-02-26T15:36:22] DEBUG1: send key up to "lap-asi2.terreactive.ch" id=61411, mask=0x0000, button=0x003c

[2025-02-26T15:36:25] DEBUG1: event: Key event kind: 12, keycode=58
[2025-02-26T15:36:25] DEBUG1: mask=80120 outMask=0004
[2025-02-26T15:36:25] DEBUG1: new mask: 0x0004
[2025-02-26T15:36:25] DEBUG1: onKeyDown id=61417 mask=0x0004 button=0x003b
[2025-02-26T15:36:25] DEBUG1: send key down to "lap-asi2.terreactive.ch" id=61417, mask=0x0004, button=0x003b

[2025-02-26T15:36:25] DEBUG1: event: Key event kind: 12, keycode=58
[2025-02-26T15:36:25] DEBUG1: mask=0100 outMask=0000
[2025-02-26T15:36:25] DEBUG1: new mask: 0x0000
[2025-02-26T15:36:25] DEBUG1: onKeyUp id=61417 mask=0x0000 button=0x003b
[2025-02-26T15:36:25] DEBUG1: send key up to "lap-asi2.terreactive.ch" id=61417, mask=0x0000, button=0x003b

[2025-02-26T15:36:27] DEBUG1: event: Key event kind: 12, keycode=55
[2025-02-26T15:36:27] DEBUG1: mask=100108 outMask=0010
[2025-02-26T15:36:27] DEBUG1: new mask: 0x0010
[2025-02-26T15:36:27] DEBUG1: onKeyDown id=61415 mask=0x0010 button=0x0038
[2025-02-26T15:36:27] DEBUG1: send key down to "lap-asi2.terreactive.ch" id=61415, mask=0x0010, button=0x0038

[2025-02-26T15:36:27] DEBUG1: event: Key event kind: 12, keycode=55
[2025-02-26T15:36:27] DEBUG1: mask=0100 outMask=0000
[2025-02-26T15:36:27] DEBUG1: new mask: 0x0000
[2025-02-26T15:36:27] DEBUG1: onKeyUp id=61415 mask=0x0000 button=0x0038
[2025-02-26T15:36:27] DEBUG1: send key up to "lap-asi2.terreactive.ch" id=61415, mask=0x0000, button=0x0038
```

**Client:**
```
[2025-02-26T15:36:22] DEBUG1: recv key down id=0x0000efe3, mask=0x0002, button=0x003c
[2025-02-26T15:36:22] DEBUG1: mapKey efe3 (61411) with mask 0002, start state: 0000
[2025-02-26T15:36:22] DEBUG1: find best:  0000 0002
[2025-02-26T15:36:22] DEBUG1: best key index 1 of 1 (exact)
[2025-02-26T15:36:22] DEBUG1: found key in group 0
[2025-02-26T15:36:22] DEBUG1: state: 0000,0000,0000
[2025-02-26T15:36:22] DEBUG1: flip: 0000 (0000 vs 0000 in 0000 - 0000)
[2025-02-26T15:36:22] DEBUG1: desired state: 0002 0000,0000,0000
[2025-02-26T15:36:22] DEBUG1: flip: 0000 (0000 vs 0002 in fffd - 6020)
[2025-02-26T15:36:22] DEBUG1: mapped to 03c, new state 0002
[2025-02-26T15:36:22] DEBUG1: keystrokes:
[2025-02-26T15:36:22] DEBUG1:   button=0x003c virtualKey=0x003b keyDown=down

[2025-02-26T15:36:22] DEBUG1: recv key up id=0x0000efe3, mask=0x0000, button=0x003c
[2025-02-26T15:36:22] DEBUG1: new state 0000
[2025-02-26T15:36:22] DEBUG1: keystrokes:
[2025-02-26T15:36:22] DEBUG1:   button=0x003c virtualKey=0x003b keyDown=up

[2025-02-26T15:36:25] DEBUG1: recv key down id=0x0000efe9, mask=0x0004, button=0x003b
[2025-02-26T15:36:25] DEBUG1: mapKey efe9 (61417) with mask 0004, start state: 0000
[2025-02-26T15:36:25] DEBUG1: find best:  0000 0004
[2025-02-26T15:36:25] DEBUG1: best key index 1 of 1 (exact)
[2025-02-26T15:36:25] DEBUG1: found key in group 0
[2025-02-26T15:36:25] DEBUG1: state: 0000,0000,0000
[2025-02-26T15:36:25] DEBUG1: flip: 0000 (0000 vs 0000 in 0000 - 0000)
[2025-02-26T15:36:25] DEBUG1: desired state: 0004 0000,0000,0000
[2025-02-26T15:36:25] DEBUG1: flip: 0000 (0000 vs 0004 in fffb - 6020)
[2025-02-26T15:36:25] DEBUG1: mapped to 03b, new state 0004
[2025-02-26T15:36:25] DEBUG1: keystrokes:
[2025-02-26T15:36:25] DEBUG1:   button=0x003b virtualKey=0x003a keyDown=down

[2025-02-26T15:36:25] DEBUG1: recv key up id=0x0000efe9, mask=0x0000, button=0x003b
[2025-02-26T15:36:25] DEBUG1: new state 0000
[2025-02-26T15:36:25] DEBUG1: keystrokes:
[2025-02-26T15:36:25] DEBUG1:   button=0x003b virtualKey=0x003a keyDown=up

[2025-02-26T15:36:27] DEBUG1: recv key down id=0x0000efe7, mask=0x0010, button=0x0038
[2025-02-26T15:36:27] DEBUG1: mapKey efe7 (61415) with mask 0010, start state: 0000
[2025-02-26T15:36:27] DEBUG1: find best:  0000 0010
[2025-02-26T15:36:27] DEBUG1: best key index 1 of 1 (exact)
[2025-02-26T15:36:27] DEBUG1: found key in group 0
[2025-02-26T15:36:27] DEBUG1: state: 0000,0000,0000
[2025-02-26T15:36:27] DEBUG1: flip: 0000 (0000 vs 0000 in 0000 - 0000)
[2025-02-26T15:36:27] DEBUG1: desired state: 0010 0000,0000,0000
[2025-02-26T15:36:27] DEBUG1: flip: 0010 (0000 vs 0010 in fff7 - 6020)
[2025-02-26T15:36:27] DEBUG1: mapped to 038, new state 0008
[2025-02-26T15:36:27] DEBUG1: keystrokes:
[2025-02-26T15:36:27] DEBUG1:   button=0x0037 virtualKey=0x0036 keyDown=down
[2025-02-26T15:36:27] DEBUG1:   button=0x0038 virtualKey=0x0037 keyDown=down
[2025-02-26T15:36:27] DEBUG1:   button=0x0037 virtualKey=0x0036 keyDown=up

[2025-02-26T15:36:27] DEBUG1: recv key up id=0x0000efe7, mask=0x0000, button=0x0038
[2025-02-26T15:36:27] DEBUG1: new state 0000
[2025-02-26T15:36:27] DEBUG1: keystrokes:
[2025-02-26T15:36:27] DEBUG1:   button=0x0038 virtualKey=0x0037 keyDown=up
```

So the Events are received by the client. But somehow not mapped correctly. 

this worked all fine on the latest version of Barrier. Unfortunately Barrier started to have unstable connection. I was hoping to fix this by switching over to input-leap. 

Hope this helps finding the issue.

**Comment by shymega** [comment]
I think this is fixed in the tree - can you try getting an artefact from GitHub Actions, and using that please?

**Comment by asidler** [comment]
I tried the version from https://github.com/input-leap/input-leap/actions/runs/13553107526 but still the same problem.
